# Generated by Django 5.1.2 on 2024-11-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0003_alter_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
